version: '3.8'

services:
  hikarilib-api:
    container_name: hikarilib-api
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - ./:/var/www/hikarilib-api
    ports:
      - "8001:8000"
    depends_on:
      - hikarilib-db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
  hikarilib-db:
    container_name: hikarilib-db
    restart: unless-stopped
    image: postgres:13-alpine
    volumes:
      - ./.database/postgres/data:/var/lib/pgsql/hikarilib/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432

