version: '3.8'

services:
  hikarilib-api:
    container_name: hikarilib-api
    build:
      context: .
      dockerfile: build/Dockerfile
#      target: dev
    command: "go run /go/src/github.com/yuminekosan/hikariLibBackend/cmd/main.go"
    volumes:
      - ./:/go/src/github.com/yuminekosan/hikariLibBackend
    ports:
      - "8001:8000"
    depends_on:
      - hikarilib-db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
  hikarilib-db:
    container_name: hikarilib-db
    restart: unless-stopped
    image: postgres:13-alpine
    volumes:
      - .:/var/lib/hikarilib
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=var/lib/hikarilib/pgdata
    ports:
      - ${DB_PORT}:5432

